app:
  env: development
  table: migrations

development:
  dialect: mysql
  datasource: user:password@tcp(host:port)/dbname?parseTime=true
testing:
  dialect: mysql
  datasource: user:password@tcp(host:port)/dbname?parseTime=true
